// This file auto generated by the Zen TFS 2010 Build Number Targets.
#include "stdafx.h"
using namespace System;
using namespace System::Reflection;
[assembly:AssemblyFileVersion ( "3.1.40717.65535" )]
